### ISSUE TITLE
the sign isn't creating, and also there aren't any errors in the console

### ISSUE THREAD

**Issue by tigre96** [poggit-orphanage/ChestShop#12] opened 2019-07-25 00:24 UTC
![image](https://user-images.githubusercontent.com/31993835/61836979-0804ec80-ae83-11e9-8aa4-6a3790cf4647.png)

the sign isn't creating, and also there aren't any errors in the console

**Comment by tigre96** [comment] 2019-07-25 00:26
![image](https://user-images.githubusercontent.com/31993835/61837115-9c6f4f00-ae83-11e9-959a-16f8cebcf689.png)

**Comment by jasonwynn10** [comment] 2019-07-25 01:20
1. Do you have debug messages enabled for the console?
2. Is that plugin downloaded from the poggit release page?
3. Do you have any other plugins that use signs as an interface? i.e. other shop plugins

**Comment by tigre96** [comment] 2019-07-26 09:54
1. no
2. yes
3. no, is a server test

**Comment by dapwestwood** [comment] 2019-07-28 04:59
> 1. Do you have debug messages enabled for the console?
> 2. Is that plugin downloaded from the poggit release page?
> 3. Do you have any other plugins that use signs as an interface? i.e. other shop plugins

is economyshop are the cause ? i had same issues too. adn i use EconomyShop plugins

**Comment by jasonwynn10** [comment] 2019-08-09 16:31
Fixed in https://github.com/poggit-orphanage/ChestShop/commit/c5adf5933f703e0ab06fb96833b838438ff161cb

**Closed by jasonwynn10** 2019-08-09 16:31 UTC
